project:
  type: website
  output-dir: docs
website:
  title: "MATH 203: Learning R"
  navbar:
    left:
      - href: topics/01-getting-started.qmd
        text: Getting Started
      - href: topics/02-working-with-data-in-R.qmd
        text: Working With Data in R
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

